# Trading Agent Development
Inspiration:
- https://www.backtrader.com/blog/posts/2015-08-16-backtesting-with-almost-no-programming/backtesting-with-almost-no-programming/ (Backtrader Platform würde einige Funktionen bereitstellen)
- https://github.com/tmorgan4/btgym_Kismuz?tab=readme-ov-file

In [1]:
import src.utils.file_management as filemgmt
import src.pipeline.preprocessing as preprocessing
from src.pipeline.preprocessing import StockPriceDataManager
import src.pipeline.predictors as predictors
from src.pipeline.predictors import LSTMPredictor, TransformerPredictor, NNPredictor, PredictorManager
from src.pipeline.rl_environments import RLTradingEnv, env_parametrisation_loop, TradeImplementor
from src.pipeline.rl_agents import MultiProductAgent 
from src.pipeline.financial_products import KOCertificate, KOCertificateSet
import src.pipeline.web_interaction as webinteraction
from src.pipeline.chatbot import WhatsAppChatbot

from itertools import product
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3 import DQN
from typing import Union, Literal
import numpy as np
import pandas as pd
import random
import enum

from pathlib import Path
import re

from tqdm import tqdm
from alpha_vantage.timeseries import TimeSeries

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from matplotlib.lines import Line2D

import matplotlib.pyplot as plt

from src.utils.file_management import most_recent_file

## Initialisation

In [2]:
#matplotlib backend:
try:
    %matplotlib macosx
except BaseException:
    %matplotlib macosx
    # sometimes takes two tries...
# opens in separate window

#%matplotlib notebook
# opens in notebook

In [3]:
ROOT = Path().resolve().parent

DATA = ROOT / "data"
DOWNLOADED_PRICES = DATA / "minutely_price_downloads"
INTERPOLATED_PRICES = DATA / "interpolated_prices_dax"
SCRAPED_RAW_DOWNLOADS = DATA / "scraped_raw_downloads_archive"

SAVED_MODELS = DATA / "saved_models"
SAVED_LSTM_MODELS = SAVED_MODELS / "lstm"
SAVED_TF_MODELS = SAVED_MODELS / "transformer"
WORKING_DIR_PREDICTORS = SAVED_MODELS / "working_dir_pred_manager"

SAVED_PORTFOLIOS = DATA / "portfolios"

SAVED_BACKTESTS = DATA / "backtests"

TRAINING_LOGS = ROOT / "output" / "rl_training_logs"

PRIVATE_FILES = ROOT / "private"
AV_API_KEY_FILE = PRIVATE_FILES / "Alpha Vantage API Key.txt"
with open(AV_API_KEY_FILE) as file: AV_API_KEY = file.read()

WIKIFOLIO_KEY_FILE = PRIVATE_FILES / "Wikifolio key.txt"
with open(WIKIFOLIO_KEY_FILE) as file: WIKIFOLIO_USER_KEY = file.read().split('\n')

CHATBOT_ENV_FILE = PRIVATE_FILES / "chatbot.env"

scenario : Literal['deployment', 'backtest'] = 'deployment'

## DataManager

In [4]:
data_manager = StockPriceDataManager(ticker_symbol='DAX',
                                    download_dir=DOWNLOADED_PRICES,
                                    interpolated_files_dir=INTERPOLATED_PRICES,
                                    alpha_vantage_api_key=AV_API_KEY,
                                    env_sampling_rate_minutes=15,
                                    is_etf_price_data=True,
                                    non_etf_time_price_tuples=[('2025-06-04 18:00:00', 24276.48),
                                                               ('2025-06-02 17:00:00', 23942.52),
                                                               ('2025-06-03 12:00:00', 23962.40),
                                                               ('2025-05-30 17:00:00', 23997.71)],
                                    include_scraped_downloads=(scenario == "deployment"),
                                     scrape_raw_download_dir=SCRAPED_RAW_DOWNLOADS,
                                    )

In [5]:
#filemgmt.most_recent_file(search_by="meta-data", directory=SCRAPED_RAW_DOWNLOADS)

In [6]:
#data_manager.update()

## PredictorManager

In [7]:
pred_manager = PredictorManager(data_manager=data_manager, initialisation_dir=SAVED_MODELS, recursive=True,
                                not_older_than_n_days=10,  # only recently fine-tuned models
                                )

In [8]:

pred_manager.get_predictors_by_type_sorted(architecture='LSTM', return_instances=False, preset_type='d1')[0]['validation_hit_rate']

0.6036036014556885

In [9]:
pred_manager.describe_preset_types()

"Preset Details:\n\nPreset 'a1':\n  - Sampling Rate: 15 minute(s)\n  - Rolling Window Size: 300 minute(s)\n  - Forecast Horizon: 180 minute(s)\n  - Prediction Time: 13.00\n\nPreset 'b1':\n  - Sampling Rate: 1 hour(s)\n  - Rolling Window Size: 42 hour(s)\n  - Forecast Horizon: 14 hour(s)\n  - Prediction Time: 16.00\n\nPreset 'b2':\n  - Sampling Rate: 1 hour(s)\n  - Rolling Window Size: 70 hour(s)\n  - Forecast Horizon: 14 hour(s)\n  - Prediction Time: 16.00\n\nPreset 'c1':\n  - Sampling Rate: 1 day(s)\n  - Rolling Window Size: 15 day(s)\n  - Forecast Horizon: 3 day(s)\n  - Prediction Time: 16.00\n\nPreset 'c2':\n  - Sampling Rate: 1 day(s)\n  - Rolling Window Size: 40 day(s)\n  - Forecast Horizon: 5 day(s)\n  - Prediction Time: 16.00\n\nPreset 'd1':\n  - Sampling Rate: 1 week(s)\n  - Rolling Window Size: 16 week(s)\n  - Forecast Horizon: 2 week(s)\n  - Prediction Time: 16.00\n\nPreset 'd2':\n  - Sampling Rate: 1 week(s)\n  - Rolling Window Size: 24 week(s)\n  - Forecast Horizon: 3 week(s)\n  - Prediction Time: 16.00\n\nPreset 'd3':\n  - Sampling Rate: 1 week(s)\n  - Rolling Window Size: 48 week(s)\n  - Forecast Horizon: 6 week(s)\n  - Prediction Time: 16.00\n\n"

In [10]:
#pred_manager.fine_tune_predictors(architectures_to_finetune=['LSTM'], types_to_finetune=["c1", "c2", "d1", "d2", "d3"], finetune_working_directory=WORKING_DIR_PREDICTORS, )  # if doing so, reinitialise pred_manager without "not_older_than_n_days"

## Portfolio

In [11]:
if scenario == "deployment":
    portfolio = KOCertificateSet.load_from_csv(
        file_path=filemgmt.most_recent_file(SAVED_PORTFOLIOS, ".csv", ["Scraped"]),
        underlying_price_series=data_manager.non_etf_env_interp_prices, )

    # update product details:
    for product in portfolio.ko_certificates:
        #product.update_product_details_from_scrape()  # often causes errors because it re-computes linear base price inference
        pass
    #portfolio.save_to_csv(SAVED_PORTFOLIOS / filemgmt.file_title("Saved Certificate Set", ".csv"))

elif scenario == "backtest":
    portfolio = KOCertificateSet.load_from_csv(
        file_path=filemgmt.most_recent_file(SAVED_PORTFOLIOS, ".csv", ["Artificial"]),
        underlying_price_series=data_manager.non_etf_env_interp_prices, )

In [13]:
#for product in portfolio.ko_certificates:
#    product.date_base_price_tuple = None
#    product.enforce_base_price_increase_per_annum()

## Backtest Schedule
https://github.com/tmorgan4/btgym_Kismuz/blob/master/btgym/strategy/base.py

In [10]:
if scenario == "backtest":
    result_frame = env_parametrisation_loop(
        env_price_series=data_manager.env_interp_prices,
        env_price_sampling_rate_minutes=data_manager.env_sampling_rate_minutes,
        env_product_set=portfolio,
        backtest_database_dir=SAVED_BACKTESTS,
        # varying params:
        predictor_instances=[
            #pred_manager.get_predictors_by_type_sorted(architecture='LSTM', preset_type='c2', return_instances=True, k_best=1),
            #pred_manager.get_predictors_by_type_sorted(architecture='LSTM', return_instances=True, k_best=2),
            pred_manager.get_predictors_by_type_sorted(architecture='LSTM',
                                                       return_instances=True, k_best=3),
            #pred_manager.get_predictors_by_type_sorted(architecture='LSTM',return_instances=True, k_best=4),
        ],
    
        # constant params:
        # 90 day expected return, sell -> buy -> highest leverage
        abs_potential_threshold_steps=[(.0025, .04, .1),
                                       ],
        # balanced, offensive, defensive
        trading_quantity_per_leverage_factor=[1, 1.25, 1.5, 1.75, 2,
                                              2.25, 2.5, 2.75, 3],
        sell_opposite_direction_if_no_cash=True,
        sell_all_opposite_products_if_no_cash=True,  #[False, True],
        include_open_leverage_category=False,
        precalculate_predictor_observations=True,
        leverage_categories=(1.0, 2.0, 3.0, 4.0, 5.0))
    result_frame

In [42]:
def describe_best_backtests(criterion: Literal['Mean', 'Median', 'SharpeRatio'] ='Mean', kbest: int = 3, not_older_than: pd.Timestamp = None) -> str:
    previous_frame = pd.read_csv(filemgmt.most_recent_file(SAVED_BACKTESTS))
    
    # select only recent
    previous_frame['date'] = pd.to_datetime(previous_frame['date'])
    if not_older_than is not None:
        previous_frame = previous_frame.loc[previous_frame['date'] >= not_older_than]
    
    # select best:
    best_tests = previous_frame.sort_values(by=criterion, ascending=False).iloc[:kbest].reset_index()
    
    output_str = f"Currently the *best backtests* {f'since {not_older_than} ' if not_older_than is not None else ''}are:\n\n"
    for ind, row in best_tests.iterrows():
        output_str += f"*{ind+1}. best configuration:*\n"
        
        def if_present_describe(key: str) -> str:
            if key in row.keys():
                return f"- {key}: {row[key]}\n"
            else:
                return ""
        
        for key in ['date', 'predictor_instances', 'abs_potential_threshold_steps', 'trading_quantity_per_leverage_factor', 'leverage_categories', 'sell_opposite_direction_if_no_cash', 'sell_all_opposite_products_if_no_cash']:
            output_str += if_present_describe(key)
        output_str += "\n"
        
    return output_str
        
print(describe_best_backtests(not_older_than=pd.Timestamp.now() - pd.Timedelta(days=30)))

Currently the *best backtests* since 2025-08-07 13:16:47.400272 are:

*1. best configuration:*
- date: 2025-08-25 00:00:00
- predictor_instances: [LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LSTM_c2_ValHR0.7051]
- abs_potential_threshold_steps: (0.0025, 0.04, 0.1)
- trading_quantity_per_leverage_factor: 2.5
- leverage_categories: (1.0, 2.0, 3.0, 4.0, 5.0)
- sell_opposite_direction_if_no_cash: True
- sell_all_opposite_products_if_no_cash: True

*2. best configuration:*
- date: 2025-08-25 00:00:00
- predictor_instances: [LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LSTM_c2_ValHR0.7051]
- abs_potential_threshold_steps: (0.0025, 0.04, 0.1)
- trading_quantity_per_leverage_factor: 2.25
- leverage_categories: (1.0, 2.0, 3.0, 4.0, 5.0)
- sell_opposite_direction_if_no_cash: True
- sell_all_opposite_products_if_no_cash: True

*3. best configuration:*
- date: 2025-08-25 00:00:00
- predictor_instances: [LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LSTM_c2_ValHR0.7051]
- abs_potential_threshold_steps: (0.0025, 0.04, 0.1)
- trading_quantity_per_leverage_factor: 2.0
- leverage_categories: (1.0, 2.0, 3.0, 4.0, 5.0)
- sell_opposite_direction_if_no_cash: True
- sell_all_opposite_products_if_no_cash: True

In [15]:
previous_frame = pd.read_csv(filemgmt.most_recent_file(SAVED_BACKTESTS))
previous_frame.sort_values(by='Mean', ascending=False)

,predictor_instances,abs_potential_threshold_steps,Mean,Median,StdDev,Min,Max,SharpeRatio,trading_quantity_per_leverage_factor,sell_opposite_direction_if_no_cash,sell_all_opposite_products_if_no_cash,include_open_leverage_category,precalculate_predictor_observations,leverage_categories,date
64,[LSTM_c2_ValHR0.9857],"(0.0025, 0.04, 0.1)",0.312303,0.257011,0.256059,-0.118853,1.912027,1.305445,2.5,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-09-16
65,[LSTM_c2_ValHR0.9857],"(0.0025, 0.04, 0.1)",0.312303,0.257011,0.256059,-0.118853,1.912027,1.305445,2.5,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-09-16
62,[LSTM_c2_ValHR0.9857],"(0.0025, 0.04, 0.1)",0.312303,0.257011,0.256059,-0.118853,1.912027,1.305445,2.5,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-09-16
63,[LSTM_c2_ValHR0.9857],"(0.0025, 0.04, 0.1)",0.312303,0.257011,0.256059,-0.118853,1.912027,1.305445,2.5,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-09-16
68,"[LSTM_c2_ValHR0.9857, LSTM_d2_ValHR0.9541]","(0.0025, 0.04, 0.1)",0.285838,0.224745,0.226622,-0.048853,1.529905,1.353757,2.5,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-09-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925]","(0.025, 0.075, 0.6)",0.006644,0.003478,0.100070,-0.291681,0.340071,0.225091,1.0,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
16,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925]","(0.035, 0.125, 0.7)",0.004820,0.001483,0.101482,-0.304426,0.339057,0.188869,1.0,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
17,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.035, 0.125, 0.7)",0.004645,-0.000053,0.101228,-0.224698,0.401642,0.179952,1.0,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
18,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.025, 0.075, 0.6)",0.004577,0.000697,0.099339,-0.230125,0.349942,0.190271,1.0,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
19,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.035, 0.125, 0.7)",0.003840,-0.000115,0.102606,-0.226911,0.387994,0.167632,1.0,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24

## Environment

In [12]:
env = RLTradingEnv(price_series=data_manager.env_interp_prices,
                   price_sampling_rate_minutes=data_manager.env_sampling_rate_minutes,
                   predictor_instances=pred_manager.get_predictors_by_type_sorted(architecture='LSTM',
                                                                                  return_instances=True, k_best=3),
                   product_set=portfolio,
                   trading_quantity_per_leverage_factor=2.5,
                   sell_opposite_direction_if_no_cash=True, sell_all_opposite_products_if_no_cash=True,
                   include_open_leverage_category=False,
                   precalculate_predictor_observations=(scenario == 'backtest'),  # FALSE MAKES SENSE ONLY FOR REDUCED N_STEPS IN BACKTEST
                   leverage_categories=(1.0, 2.0, 3.0, 4.0, 5.0))  #, 5.5, 6.0, 6.5, 7.0))

Starting at 2015-9-24 although data is provided since 2014-10-23 to have sufficient information for all predictors.

In [13]:
#obs, _, _, _, info = env.step(3, track_portfolio_exposure=False)
#print(obs)
#print(info)
#self.open_positions"""

## Agent

### Manual Agent

In [14]:
agent = MultiProductAgent(observation_types=env.observation_types,
                          observation_horizons_minute=env.observation_horizons_minutes,
                          n_leverage_categories=len(env.leverage_categories),
                          abs_potential_threshold_steps=(.0025, .04, .1),  # (.04, .15, .7)
                          include_open_leverage_category=env.include_open_leverage_category,
                          potential_treshold_horizon_days=env.potential_horizon_days,
                          )

### RL Agent
With stable-baseline3 and pytorch.

Stable-Baselines3 is a reinforcement learning library built on top of PyTorch. It provides a set of pre-implemented RL algorithms and simplifies the process of training and evaluating RL models. It also includes a variety of useful tools for monitoring training progress and visualizing model behavior.

For training we will use Deep Q-Network (DQN). DQN is a reinforcement learning algorithm that uses a deep neural network to approximate the Q-value function. The Q-value function is a function that receives a status-action pair and outputs a value representing the expected cumulative reward for taking that action from that status, and continues playing following the optimal policy.

#### Agent Training

In [15]:
from stable_baselines3.common.env_checker import check_env
# check_env(env)

In [16]:
# MlpPolicy is policy used for training
# DummyVecEnc optimizes training through multiple independent variables
#env.verbose = False  # mute environment
#rl_agent = DQN('MlpPolicy', DummyVecEnv([lambda: env]), learning_rate=0.001, verbose=1)

In [17]:
#rl_agent.learn(total_timesteps=50000, log_interval=100, progress_bar=True)  # ~1s per iteration -> ~3600 iterations/h
#rl_agent.save(filemgmt.file_title('DQN Trading Agent 100k iterations', dtype_suffix='.pt'))

In [18]:
# only decision 'sell long 2.0-3.0' in backtest... what can cause stagnant decision-making?

In [19]:
# ponder:
# - training visualisation
# - reward shaping
# - initialisation
# - architecture

## Single Backtest

In [20]:
"""monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=rl_agent, track_portfolio_exposure_every=20,
                                                         reset_environment=True,
                                                         save_log_directory=TRAINING_LOGS, performance_time_unit='p.m.')"""

"monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=rl_agent, track_portfolio_exposure_every=20,\n                                                         reset_environment=True,\n                                                         save_log_directory=TRAINING_LOGS, performance_time_unit='p.m.')"

In [21]:
if scenario == 'backtest':
    monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=agent, track_portfolio_exposure_every=20,
                                                                         reset_environment=True,
                                                                         save_log_directory=TRAINING_LOGS,
                                                                         performance_time_unit='p.m.')

## Deployment

In [15]:
env.current_step = env.total_steps - 2
env.current_step_timestamp

Timestamp('2025-09-16 16:00:00')

In [20]:
env.compute_predicted_prices()

{'LSTM_d3_ValHR0.9904': (date
  2024-10-15 16:00:00    34.568936
  2024-10-22 16:00:00    34.453670
  2024-10-29 16:00:00    34.149329
  2024-11-05 16:00:00    33.971208
  2024-11-12 16:00:00    32.968294
  2024-11-19 16:00:00    32.411862
  2024-11-26 16:00:00    32.771294
  2024-12-03 16:00:00    33.987900
  2024-12-10 16:00:00    34.716983
  2024-12-17 16:00:00    34.522544
  2024-12-24 16:00:00    33.672974
  2024-12-31 16:00:00    33.426417
  2025-01-07 16:00:00    34.239900
  2025-01-14 16:00:00    33.798125
  2025-01-21 16:00:00    35.401585
  2025-01-28 16:00:00    36.264323
  2025-02-04 16:00:00    36.050000
  2025-02-11 16:00:00    36.915000
  2025-02-18 16:00:00    38.698588
  2025-02-25 16:00:00    38.322500
  2025-03-04 16:00:00    38.312500
  2025-03-11 16:00:00    39.950000
  2025-03-18 16:00:00    41.200000
  2025-03-25 16:00:00    40.440000
  2025-04-01 16:00:00    39.155000
  2025-04-08 16:00:00    36.110000
  2025-04-15 16:00:00    38.990000
  2025-04-22 16:00:00    39.380000
  2025-04-29 16:00:00    41.440000
  2025-05-06 16:00:00    42.590000
  2025-05-13 16:00:00    42.560000
  2025-05-20 16:00:00    43.650000
  2025-05-27 16:00:00    44.380000
  2025-06-03 16:00:00    44.100000
  2025-06-10 16:00:00    43.717400
  2025-06-17 16:00:00    42.602000
  2025-06-24 16:00:00    43.885200
  2025-07-01 16:00:00    44.510000
  2025-07-08 16:00:00    45.330000
  2025-07-15 16:00:00    44.440000
  2025-07-22 16:00:00    45.060000
  2025-07-29 16:00:00    44.500000
  2025-08-05 16:00:00    43.980000
  2025-08-12 16:00:00    44.860000
  2025-08-19 16:00:00    45.170000
  2025-08-26 16:00:00    44.910000
  2025-09-02 16:00:00    43.750100
  2025-09-09 16:00:00    44.330000
  Name: close, dtype: float64,
  2025-09-12 14:00:00    44.825155
  2025-09-15 12:00:00    44.765299
  2025-09-18 10:00:00    44.739472
  2025-09-21 08:00:00    44.719291
  2025-09-24 06:00:00    44.702333
  2025-09-27 04:00:00    44.688744
  Freq: 4200min, dtype: float64),
 'LSTM_c2_ValHR0.9857': (date
  2025-07-22 16:00:00    45.060000
  2025-07-23 16:00:00    45.980000
  2025-07-24 16:00:00    45.420000
  2025-07-25 16:00:00    45.450000
  2025-07-28 16:00:00    44.240000
  2025-07-29 16:00:00    44.500000
  2025-07-30 16:00:00    44.140000
  2025-07-31 16:00:00    43.660000
  2025-08-01 16:00:00    43.160000
  2025-08-04 16:00:00    43.790000
  2025-08-05 16:00:00    43.980000
  2025-08-06 16:00:00    44.420000
  2025-08-07 16:00:00    44.910000
  2025-08-08 16:00:00    44.900000
  2025-08-11 16:00:00    44.490000
  2025-08-12 16:00:00    44.860000
  2025-08-13 16:00:00    45.105000
  2025-08-14 16:00:00    45.304800
  2025-08-15 16:00:00    45.380000
  2025-08-18 16:00:00    45.250000
  2025-08-19 16:00:00    45.170000
  2025-08-20 16:00:00    45.060000
  2025-08-21 16:00:00    44.820000
  2025-08-22 16:00:00    45.430000
  2025-08-25 16:00:00    44.830000
  2025-08-26 16:00:00    44.910000
  2025-08-27 16:00:00    44.340000
  2025-08-28 16:00:00    44.690000
  2025-08-29 16:00:00    44.570000
  2025-09-01 16:00:00    44.322544
  2025-09-02 16:00:00    43.750100
  2025-09-03 16:00:00    43.830000
  2025-09-04 16:00:00    44.230000
  2025-09-05 16:00:00    44.099600
  2025-09-08 16:00:00    44.590000
  2025-09-09 16:00:00    44.330000
  2025-09-10 16:00:00    43.960000
  2025-09-11 16:00:00    44.390000
  2025-09-12 16:00:00    44.260000
  2025-09-15 16:00:00    44.449600
  Name: close, dtype: float64,
  2025-09-16 06:00:00    44.286053
  2025-09-16 20:00:00    44.384373
  2025-09-17 10:00:00    44.298127
  2025-09-18 00:00:00    44.368073
  2025-09-18 14:00:00    44.340377
  Freq: 840min, dtype: float64),
 'LSTM_d3_ValHR0.9808': (date
  2024-10-15 16:00:00    34.568936
  2024-10-22 16:00:00    34.453670
  2024-10-29 16:00:00    34.149329
  2024-11-05 16:00:00    33.971208
  2024-11-12 16:00:00    32.968294
  2024-11-19 16:00:00    32.411862
  2024-11-26 16:00:00    32.771294
  2024-12-03 16:00:00    33.987900
  2024-12-10 16:00:00    34.716983
  2024-12-17 16:00:00    34.522544
  2024-12-24 16:00:00    33.672974
  2024-12-31 16:00:00    33.426417
  2025-01-07 16:00:00    34.239900
  2025-01-14 16:00:00    33.798125
  2025-01-21 16:00:00    35.401585
  2025-01-28 16:00:00    36.264323
  2025-02-04 16:00:00    36.050000
  2025-02-11 16:00:00    36.915000
  2025-02-18 16:00:00    38.698588
  2025-02-25 16:00:00    38.322500
  2025-03-04 16:00:00    38.312500
  2025-03-11 16:00:00    39.950000
  2025-03-18 16:00:00    41.200000
  2025-03-25 16:00:00    40.440000
  2025-04-01 16:00:00    39.155000
  2025-04-08 16:00:00    36.110000
  2025-04-15 16:00:00    38.990000
  2025-04-22 16:00:00    39.380000
  2025-04-29 16:00:00    41.440000
  2025-05-06 16:00:00    42.590000
  2025-05-13 16:00:00    42.560000
  2025-05-20 16:00:00    43.650000
  2025-05-27 16:00:00    44.380000
  2025-06-03 16:00:00    44.100000
  2025-06-10 16:00:00    43.717400
  2025-06-17 16:00:00    42.602000
  2025-06-24 16:00:00    43.885200
  2025-07-01 16:00:00    44.510000
  2025-07-08 16:00:00    45.330000
  2025-07-15 16:00:00    44.440000
  2025-07-22 16:00:00    45.060000
  2025-07-29 16:00:00    44.500000
  2025-08-05 16:00:00    43.980000
  2025-08-12 16:00:00    44.860000
  2025-08-19 16:00:00    45.170000
  2025-08-26 16:00:00    44.910000
  2025-09-02 16:00:00    43.750100
  2025-09-09 16:00:00    44.330000
  Name: close, dtype: float64,
  2025-09-12 14:00:00    44.483462
  2025-09-15 12:00:00    44.369989
  2025-09-18 10:00:00    44.282657
  2025-09-21 08:00:00    44.207118
  2025-09-24 06:00:00    44.144400
  2025-09-27 04:00:00    44.096032
  Freq: 4200min, dtype: float64)}

In [36]:
mpl_palette: str = 'Set1'
zoom_on_last_n_days: int = 40
displayed_potential_tolerance: float = 0.5

from datetime import datetime

price_dict = env.compute_predicted_prices()
##### prepare plots:
fig, axs = plt.subplots(
    len(price_dict)+1,  # an extra row for each predictor
    1, figsize=(10, 10),
    gridspec_kw={'height_ratios': [3, 1, 1, 1]}  # compound upper plot 3x height
)
compound_ax = axs[0]; compound_ax.set_title('All Predictors')
cmap = plt.colormaps[mpl_palette]
color_list = [cmap(i) for i in range(len(price_dict))]

# predictor with smallest timescale:
finest_predictor_ind = np.argmin([pred.sampling_rate_minutes for pred in env.predictor_instances])
displayed_features = None  # will be efficiently inferred in for loop

##### single prediction plotting:
for pred_ind, (pred_name, (features, prediction)) in enumerate(price_dict.items()):
    # compound ax plot:
    if pred_ind == finest_predictor_ind:  # features only for predictor with finest time-resolution
        compound_ax.plot(features.index, features, marker='o', markevery=[-1], color='darkblue')
        displayed_features = features.copy()
    compound_ax.plot(prediction.index, prediction, marker='o', markevery=[-1], color=color_list[pred_ind], label=pred_name, linestyle='dashed')
    
    # single ax plot:
    pred_ax = axs[pred_ind+1]
    pred_ax.plot(features.index, features, marker='o', markevery=[-1], color='darkblue', label='Features')
    pred_ax.plot(prediction.index, prediction, marker='o', markevery=[-1], color=color_list[pred_ind], label='Predictions', linestyle='dashed')
    pred_ax.set_title(pred_name)

##### include average potential in compound plot:
if displayed_features is None:
    displayed_features = features.copy()
avg_predicted_price = displayed_features.iloc[-1] * (1 + env.current_avg_scaled_predicted_potential)
# if less or more of the potential is realised:
prediction_cone = (displayed_features.iloc[-1] * (1 + env.current_avg_scaled_predicted_potential * (1 - displayed_potential_tolerance)),
                   displayed_features.iloc[-1] * (1 + env.current_avg_scaled_predicted_potential * (1 + displayed_potential_tolerance)))
# assert that first element is the smaller one:
prediction_cone = (min(prediction_cone), max(prediction_cone))

avg_predicted_price_date = displayed_features.index.max() + pd.Timedelta(days=env.potential_horizon_days)
plot_dates = [displayed_features.index.max(), avg_predicted_price_date]
last_feature_value = displayed_features.iloc[-1]
compound_ax.plot(plot_dates,
                 [last_feature_value, avg_predicted_price], marker='X', color='Blue', label='Average Predicted Potential')
compound_ax.fill_between(
    x=plot_dates,
    y1=[last_feature_value, prediction_cone[0]],
    y2=[last_feature_value, prediction_cone[1]],
    color='blue',
    alpha=0.2,
    label='Prediction Cone'
)


##### eventual zoom-in:
if zoom_on_last_n_days is not None:
    # adjust x-axis limits:
    start_date = datetime.now() - pd.Timedelta(days=zoom_on_last_n_days)
    compound_ax.set_xlim(start_date, None)
    
    # filter the data within the new x_lim
    all_values = pd.concat([tuple[0] for tuple in price_dict.values()] + [tuple[1] for tuple in price_dict.values()])
    visible_data = all_values[(all_values.index >= start_date)]
    
    # compute new y_lim based on the visible data and prediction cone:
    new_y_min = min(visible_data.min().min(), prediction_cone[0])
    new_y_max = max(visible_data.max().max(), prediction_cone[1])
    compound_ax.set_ylim(new_y_min - (new_y_max - new_y_min)*.05,
                         new_y_max + (new_y_max - new_y_min)*.05)


##### formatting:
for ax in axs:
    ax.set_ylabel('Prices [USD]')
    if ax == axs[-1]: ax.set_xlabel('Date')
    ax.legend()
    ax.grid()
fig.tight_layout()

In [23]:
pred_name

date
2024-10-15 16:00:00    34.568936
2024-10-22 16:00:00    34.453670
2024-10-29 16:00:00    34.149329
2024-11-05 16:00:00    33.971208
2024-11-12 16:00:00    32.968294
2024-11-19 16:00:00    32.411862
2024-11-26 16:00:00    32.771294
2024-12-03 16:00:00    33.987900
2024-12-10 16:00:00    34.716983
2024-12-17 16:00:00    34.522544
2024-12-24 16:00:00    33.672974
2024-12-31 16:00:00    33.426417
2025-01-07 16:00:00    34.239900
2025-01-14 16:00:00    33.798125
2025-01-21 16:00:00    35.401585
2025-01-28 16:00:00    36.264323
2025-02-04 16:00:00    36.050000
2025-02-11 16:00:00    36.915000
2025-02-18 16:00:00    38.698588
2025-02-25 16:00:00    38.322500
2025-03-04 16:00:00    38.312500
2025-03-11 16:00:00    39.950000
2025-03-18 16:00:00    41.200000
2025-03-25 16:00:00    40.440000
2025-04-01 16:00:00    39.155000
2025-04-08 16:00:00    36.110000
2025-04-15 16:00:00    38.990000
2025-04-22 16:00:00    39.380000
2025-04-29 16:00:00    41.440000
2025-05-06 16:00:00    42.590000
2025-05-13 16:00:00    42.560000
2025-05-20 16:00:00    43.650000
2025-05-27 16:00:00    44.380000
2025-06-03 16:00:00    44.100000
2025-06-10 16:00:00    43.717400
2025-06-17 16:00:00    42.602000
2025-06-24 16:00:00    43.885200
2025-07-01 16:00:00    44.510000
2025-07-08 16:00:00    45.330000
2025-07-15 16:00:00    44.440000
2025-07-22 16:00:00    45.060000
2025-07-29 16:00:00    44.500000
2025-08-05 16:00:00    43.980000
2025-08-12 16:00:00    44.860000
2025-08-19 16:00:00    45.170000
2025-08-26 16:00:00    44.910000
2025-09-02 16:00:00    43.750100
2025-09-09 16:00:00    44.330000
Name: close, dtype: float64

### Scrape Real-Time Data

#### DAX Price

In [22]:
if scenario == "deployment":
    # update interpolated data with scraping:
    data_manager.update(force_include_scraped=True)
    
    env.price_series = data_manager.env_interp_prices
    portfolio.update_all_price_series(data_manager.non_etf_env_interp_prices)
    
    # here one more step can be executed:
    env.current_step = env.total_steps - 2
    env.current_step_timestamp

Downloaded data ranged from	2014-10-23 15:31:00 to 2025-08-28 18:18:00
Will query the AlphaVantage API 2 times based on the specified time range. Queries:
 ['2025-08', '2025-09']

100%|██████████| 2/2 [00:01<00:00,  1.54it/s]

Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_INTRADAY.

now ranges from				2014-10-23 15:31:00 to 2025-08-29 16:10:00

Interpolated data ranged from	2014-10-23 16:00:00 to 2025-08-29 16:30:00
Successfully downloaded price data from comdirect.
now ranges from					2014-10-23 16:00:00 to 2025-08-29 16:30:00

#### Wikifolio Data

In [23]:
# login to wikifolio:
driver = webinteraction.login_to_wikifolio(WIKIFOLIO_USER_KEY[0], WIKIFOLIO_USER_KEY[1])

In [24]:
# fetch relevant portfolio data:
wf_cash, wf_value, wf_shares_p_isin, wf_price_p_isin = webinteraction.scrape_portfolio_holdings_from_wikifolio(driver)

In [25]:
# update env cash:
env.cash = wf_cash

# update shares per product:
for isin, shares in wf_shares_p_isin.items():
    env.shares_per_product[isin] = shares

In [26]:
# derive price deviations:
closest_to_current_prices = env.product_set.price_frame.loc[:pd.Timestamp.now()].iloc[-1]
print(f"-------------------- Simulated product price deviations --------------------")
for isin, price in wf_price_p_isin.items():
    if isin in closest_to_current_prices.index:
        deviation = (closest_to_current_prices[isin] / price - 1) * 100
        print(f"{isin}:  {deviation:.2f}%\t\t(Env. price: {price:.2f},  \tWF price: {closest_to_current_prices[isin]:.2f})")

-------------------- Simulated product price deviations --------------------
DE000SX0LHS4:  -2.07%		(Env. price: 71.29,  	WF price: 69.82)
DE000FA0RD26:  -2.32%		(Env. price: 98.29,  	WF price: 96.01)
DE000HG75555:  1.79%		(Env. price: 94.43,  	WF price: 96.12)
DE000HS3GYD5:  2.85%		(Env. price: 6.59,  	WF price: 6.78)
DE000HS8DSJ0:  4.20%		(Env. price: 5.69,  	WF price: 5.93)
DE000TT0ZP72:  1.18%		(Env. price: 147.92,  	WF price: 149.67)
DE000TT1K2J8:  1.99%		(Env. price: 157.70,  	WF price: 160.83)
DE000TT1WHV8:  1.44%		(Env. price: 118.26,  	WF price: 119.97)
DE000TT2CH77:  1.60%		(Env. price: 106.86,  	WF price: 108.56)
DE000FA0Q232:  -2.71%		(Env. price: 83.19,  	WF price: 80.94)
DE000HS2W424:  3.53%		(Env. price: 7.53,  	WF price: 7.80)
DE000HS3U0K3:  2.70%		(Env. price: 6.07,  	WF price: 6.23)
DE000HT52AV7:  -3.42%		(Env. price: 56.13,  	WF price: 54.21)

In [27]:
add_missing = False

# see whether all product_set isins are included in wikifolio:
missing_isins = []
for product in env.product_set.ko_certificates:
    if product.isin not in wf_shares_p_isin.keys():
        print(f"Product {product.isin} not found in WF portfolio. {'Will be added.' if add_missing else 'Consider adding.'}")
        missing_isins.append(product.isin)
    
if add_missing: webinteraction.add_products_to_wikifolio(driver, missing_isins)

### Chatbot

In [28]:
chatter = WhatsAppChatbot("../private/chatbot.env", verbose=True)

In [29]:
chatter("Hey! I just fetched wikifolio's statistics and today's price data. Now inferring today's predictions.")
chatter(f"Currently the environment is at {env.current_step_timestamp}.")

401
{"error":{"message":"Error validating access token: Session has expired on Monday, 01-Sep-25 03:00:00 PDT. The current time is Monday, 01-Sep-25 10:03:29 PDT.","type":"OAuthException","code":190,"error_subcode":463,"fbtrace_id":"A05nDHjMNlFowZ5TP5aIQJR"}}
401
{"error":{"message":"Error validating access token: Session has expired on Monday, 01-Sep-25 03:00:00 PDT. The current time is Monday, 01-Sep-25 10:03:30 PDT.","type":"OAuthException","code":190,"error_subcode":463,"fbtrace_id":"A8i_N3J0vneeNDTbebxMjtO"}}

### Inference

In [30]:
env.open_positions

                Shares  Leverage     Price Direction  % Portfolio
DE000HS8DSJ0  168248.0  4.039224  6.024614      long    95.889202

In [32]:
env.open_positions

                Shares  Leverage     Price Direction  % Portfolio
DE000HS8DSJ0  168248.0  4.039224  6.024614      long    95.889202

In [33]:
action, _ = agent.predict(env.current_observation)
trade_implementor = TradeImplementor()
new_obs, _, done, truncated, info = env.step(action, track_portfolio_exposure=False, start_new_episode_if_finished=False,
                                             trade_implementation_callback=trade_implementor)
print(info)

[STEP 2831] Bought 7287.0 shares of DE000HS8DSJ0 (long with leverage in (4.0, 5.0)) at 5.962905095611968.
    Cash: 2.8925682755871094, Holding: 1045652.8930651818
{'Step': 2831, 'Time': '2025-08-29 16:00:00', 'Reward': -11427.99, 'Action': 'Buy long 4.0x - 5.0x', 'Avg. Expected Potential / 90d': 0.23024521491521685, 'Cash': 2.89, 'Total': 1045655.79}

In [34]:
predictions_str_list = [f"{round(potential*100, 2)} % in {round(horizon_minutes / 60 / 14)} days" for potential, horizon_minutes in zip(env.current_potential_estimates, env.observation_horizons_minutes)]
prediction_str = "\n".join(predictions_str_list)  # will be included in next str:

In [35]:
explanatory_string = f"Based on the predictions\n\n{prediction_str}\n\n-> an average predicted potential of {env.current_avg_scaled_predicted_potential*100:.2f} % in {env.potential_horizon_days} days, the agent wants to {info['Action']}!"
explanatory_string

'Based on the predictions\n\n2.41 % in 5 days\n-0.01 % in 30 days\n-0.5 % in 15 days\n\n-> an average predicted potential of 23.02 % in 90 days, the agent wants to Buy long 4.0x - 5.0x!'

In [36]:
chatter(explanatory_string)

401
{"error":{"message":"Error validating access token: Session has expired on Monday, 01-Sep-25 03:00:00 PDT. The current time is Monday, 01-Sep-25 10:03:31 PDT.","type":"OAuthException","code":190,"error_subcode":463,"fbtrace_id":"AIAvfusDwjJG6EJGi5QxEry"}}

### Execution

In [37]:
chatter(f"Currently we have {wf_cash} EUR cash in the wikifolio ({wf_cash / wf_value * 100:.2f}%).")

401
{"error":{"message":"Error validating access token: Session has expired on Monday, 01-Sep-25 03:00:00 PDT. The current time is Monday, 01-Sep-25 10:03:31 PDT.","type":"OAuthException","code":190,"error_subcode":463,"fbtrace_id":"ALRdEGyAVjmhUMhI5jPxO26"}}

In [38]:
trade_str_list = []
for trade_dict in trade_implementor.action_log.values():
    if trade_dict["completed"]: continue  # only uncompleted trade
    
    trade_str_list.append(f"{trade_dict['action']} {trade_dict['amount'].item() if isinstance(trade_dict['amount'], np.float16) else trade_dict['amount']} shares of {trade_dict['isin']}.")

chatter("The resulting recommended trades are:")
for trade_str in trade_str_list:
    chatter(trade_str)

401
{"error":{"message":"Error validating access token: Session has expired on Monday, 01-Sep-25 03:00:00 PDT. The current time is Monday, 01-Sep-25 10:03:32 PDT.","type":"OAuthException","code":190,"error_subcode":463,"fbtrace_id":"Ahw3PVmdkxIBbwJFBUHU6Iq"}}
401
{"error":{"message":"Error validating access token: Session has expired on Monday, 01-Sep-25 03:00:00 PDT. The current time is Monday, 01-Sep-25 10:03:32 PDT.","type":"OAuthException","code":190,"error_subcode":463,"fbtrace_id":"Ahv6fXpeGJ1qbRPt8p49Pw6"}}

In [39]:
chatter(f"Now the environment is at {env.current_step_timestamp}.")

401
{"error":{"message":"Error validating access token: Session has expired on Monday, 01-Sep-25 03:00:00 PDT. The current time is Monday, 01-Sep-25 10:03:32 PDT.","type":"OAuthException","code":190,"error_subcode":463,"fbtrace_id":"AaekHK4Dq8ScnPyNPcpDjrm"}}