# Trading Agent Development
Inspiration:
- https://www.backtrader.com/blog/posts/2015-08-16-backtesting-with-almost-no-programming/backtesting-with-almost-no-programming/ (Backtrader Platform würde einige Funktionen bereitstellen)
- https://github.com/tmorgan4/btgym_Kismuz?tab=readme-ov-file
-

In [1]:
import src.utils.file_management as filemgmt
import src.pipeline.preprocessing as preprocessing
import src.pipeline.predictors as predictors
from src.pipeline.predictors import LSTMPredictor, TransformerPredictor
from src.pipeline.rl_environments import RLTradingEnv
from src.pipeline.rl_agents import MultiProductAgent 
from src.pipeline.financial_products import KOCertificate, KOCertificateSet

from itertools import product
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3 import DQN
from typing import Union, Literal
import numpy as np
import pandas as pd
import random
import enum

from pathlib import Path

from tqdm import tqdm
from alpha_vantage.timeseries import TimeSeries

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from matplotlib.lines import Line2D

import matplotlib.pyplot as pl

## Initialisation

In [2]:
#matplotlib backend:
try:
    %matplotlib macosx
except BaseException:
    %matplotlib macosx
    # sometimes takes two tries...
    
# opens in separate window

#%matplotlib notebook
# opens in notebook

In [3]:
ROOT = Path().resolve().parent

DATA = ROOT / "data"
INTERPOLATED_PRICES = DATA / "interpolated_prices_dax"

SAVED_LSTM_MODELS = DATA / "saved_models" / "lstm"
SAVED_TF_MODELS = DATA / "saved_models" / "transformer"

TRAINING_LOGS = ROOT / "output" / "rl_training_logs"

PRIVATE_FILES = ROOT / "private"
AV_API_KEY_FILE = PRIVATE_FILES / "Alpha Vantage API Key.txt"
with open(AV_API_KEY_FILE) as file: AV_API_KEY = file.read()

In [4]:
# hourly data:
SAVED_B1_LSTM_PRED_556 = SAVED_LSTM_MODELS / "b_hourly_data" / "2025-07-28 13_16_18 LSTM Model RW42 FH14 Layers4 Size256 TrainL0.2269753264845349 ValL0.05964132840745151 TrainHR0.5311934947967529 ValHR0.5559566617012024.pt"
SAVED_B2_LSTM_PRED_557 = SAVED_LSTM_MODELS / "b_hourly_data" / "2025-07-28 15_54_59 LSTM Model RW70 FH14 Layers3 Size256 TrainL0.30958290363196284 ValL0.09781504119746387 TrainHR0.5377657413482666 ValHR0.5569620132446289.pt"

SAVED_B1_TF_PRED_542 = SAVED_TF_MODELS / "b_hourly_data" / "2025-07-29 05_00_35 Transformer Model RW42 FH14 Layers3 Size512 Heads16 TrainL0.6157988728955388 ValL0.3280078349635005 TrainHR0.49547919631004333 ValHR0.5415162444114685.pt"

# daily data:
SAVED_C1_LSTM_PRED_619 = SAVED_LSTM_MODELS / "c_daily_data" / "2025-07-29 10_52_54 LSTM Model RW15 FH3 Layers4 Size256 TrainL0.5109546836465597 ValL0.15437627281062305 TrainHR0.6462306976318359 ValHR0.6188747882843018.pt"
SAVED_C2_LSTM_PRED_705 = SAVED_LSTM_MODELS / "c_daily_data" / "2025-07-29 11_10_59 LSTM Model RW40 FH5 Layers3 Size256 TrainL0.5822748932987452 ValL0.1824055234901607 TrainHR0.7123852968215942 ValHR0.7051281929016113.pt"

SAVED_C1_TF_PRED_534 = SAVED_TF_MODELS / "c_daily_data" / "2025-07-29 12_24_40 Transformer Model RW15 FH3 Layers3 Size512 Heads16 TrainL2.661198813468218 ValL0.8520454280078411 TrainHR0.5399636626243591 ValHR0.5335752964019775.pt"
SAVED_C2_TF_PRED_542 = SAVED_TF_MODELS / "c_daily_data" / "2025-07-29 12_48_04 Transformer Model RW40 FH5 Layers3 Size256 Heads16 TrainL2.4900605091825128 ValL0.5748474728316069 TrainHR0.5307339429855347 ValHR0.5421245694160461.pt"

# weekly data:
SAVED_D1_LSTM_PRED_667 = SAVED_LSTM_MODELS / "d_weekly_data" / "2025-07-29 14_10_26 LSTM Model RW16 FH2 Layers4 Size256 TrainL0.39238258823752403 ValL0.11338997259736061 TrainHR0.5687645673751831 ValHR0.6666666865348816.pt"
SAVED_D2_LSTM_PRED_792 = SAVED_LSTM_MODELS / "d_weekly_data" / "2025-07-29 14_15_20 LSTM Model RW24 FH3 Layers3 Size256 TrainL0.2899367194622755 ValL0.09412111341953278 TrainHR0.741706132888794 ValHR0.7924528121948242.pt"
SAVED_D3_LSTM_PRED_911 = SAVED_LSTM_MODELS / "d_weekly_data" / "2025-07-29 14_32_49 LSTM Model RW48 FH6 Layers4 Size256 TrainL0.1885785385966301 ValL0.05248359590768814 TrainHR0.8924999833106995 ValHR0.9108911156654358.pt"

SAVED_D1_TF_PRED_574 = SAVED_TF_MODELS / "d_weekly_data" / "2025-08-04 12_26_55 Transformer Model RW16 FH2 Layers2 Size256 Heads16 TrainL1.084182608872652 ValL0.2614380903542042 TrainHR0.5477855205535889 ValHR0.5740740895271301.pt"
SAVED_D2_TF_PRED_613 = SAVED_TF_MODELS / "d_weekly_data" / "2025-07-17 17_41_32 Transformer Model RW24 FH3 Layers6 Size256 Heads16 TrainL0.3821653798222542 ValL0.07798176817595959 TrainHR0.5734597444534302 ValHR0.6132075190544128.pt"
SAVED_D3_TF_PRED_743 = SAVED_TF_MODELS / "d_weekly_data" / "2025-07-29 14_56_59 Transformer Model RW48 FH6 Layers3 Size256 Heads8 TrainL1.404388252645731 ValL0.5182094983756542 TrainHR0.7200000286102295 ValHR0.7425742745399475.pt"

In [5]:
ENV_PRICE_FILE = filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '15min')  #filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '15min')
B_PRICE_FILE = filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '60min')
C_PRICE_FILE = filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '1d')
D_PRICE_FILE = filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '7d')
MEAN_ETF_INDEX_RATIO = 543.3079783216567  # because files are etf prices

## Products

In [6]:
'''dax_long1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
                         isin='DE000TT2CH77',
                         date_base_price_tuple2=("2022-09-26 12:00:00", 10300)
                         # historic_date_future_price_tuple=("2022-09-26", 6.49),
                        )
dax_long1.plot()

dax_long1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
                         isin='DE000TT2CH77',
                         date_base_price_tuple2=("2022-09-26 12:00:00", 10300)
                         # historic_date_future_price_tuple=("2022-09-26", 6.49),
                        )
dax_long1.plot()

dax_long2 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
                         isin='DE000HS3U0K3',
                          direction='long',
                        )

dax_short1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
                         isin='DE000HT2PK31',
                         #historic_date_future_price_tuple=("2024-01-08", 1.31),
                        )
dax_short1.plot()

dax_short2 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
                         isin='DE000HT2LDF5',
                        )
dax_short2.plot()'''

'dax_long1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,\n                         isin=\'DE000TT2CH77\',\n                         date_base_price_tuple2=("2022-09-26 12:00:00", 10300)\n                         # historic_date_future_price_tuple=("2022-09-26", 6.49),\n                        )\ndax_long1.plot()\n\ndax_long1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,\n                         isin=\'DE000TT2CH77\',\n                         date_base_price_tuple2=("2022-09-26 12:00:00", 10300)\n                         # historic_date_future_price_tuple=("2022-09-26", 6.49),\n                        )\ndax_long1.plot()\n\ndax_long2 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,\n                         isin=\'DE000HS3U0K3\',\n                          direction=\'long\',\n                        )\n\ndax_short1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,\n                         isin=\'DE000HT2PK31\',\n                         #historic_date_future_price_tuple=("2024-01-08", 1.31),\n                        )\ndax_short1.plot()\n\ndax_short2 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,\n                         isin=\'DE000HT2LDF5\',\n                        )\ndax_short2.plot()'

### Portfolio Construction

In [7]:
# initialise for 2020/07, 2022/07, 2024/01
portfolio = KOCertificateSet(
    underlying_price_series=preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
    base_price_inference_timestamps=["2020-07-06 10:00:00", "2022-07-05 10:00:00", "2024-01-05 10:00:00"], # "2023-07-05 10:00:00", "2024-07-05 10:00:00", "2025-03-05 10:00:00"],
    n_products_per_direction=15,
    lowest_leverage=1.0, highest_leverage=10.0)

# add several other with more recent issue dates
portfolio.future_product_instances += portfolio.initialise_products_from_leverage(underlying_price_series=preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
    base_price_inference_timestamps=["2017-12-08 10:00:00", "2018-07-05 10:00:00"],
    n_products_per_direction=15, issue_date="2017-01-01 10:00:00",
    lowest_leverage=1.0, highest_leverage=10.0)

portfolio.future_product_instances += portfolio.initialise_products_from_leverage(underlying_price_series=preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
    base_price_inference_timestamps=["2021-07-06 10:00:00", "2023-07-05 10:00:00", "2024-07-05 10:00:00", "2025-03-05 10:00:00"],
    n_products_per_direction=15, issue_date="2020-06-01 10:00:00",
    lowest_leverage=1.0, highest_leverage=10.0)

portfolio.future_product_instances += portfolio.initialise_products_from_leverage(underlying_price_series=preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
    base_price_inference_timestamps=["2023-05-05 10:00:00", "2024-07-05 10:00:00", "2025-03-05 10:00:00"],
    n_products_per_direction=15, issue_date="2022-12-01 10:00:00",
    lowest_leverage=1.0, highest_leverage=10.0)

portfolio.future_product_instances += portfolio.initialise_products_from_leverage(underlying_price_series=preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
    base_price_inference_timestamps=["2025-03-05 12:00:00"],
    n_products_per_direction=15, issue_date="2024-03-03 10:00:00",
    lowest_leverage=1.0, highest_leverage=10.0)

30it [00:00, 40.35it/s]
30it [00:00, 47.24it/s]
30it [00:00, 40.67it/s]
30it [00:01, 29.66it/s]
30it [00:01, 26.73it/s]
30it [00:00, 40.82it/s]
30it [00:00, 34.68it/s]
30it [00:00, 31.96it/s]
30it [00:00, 36.81it/s]
30it [00:00, 64.68it/s]
30it [00:00, 56.42it/s]
30it [00:00, 48.39it/s]
30it [00:00, 69.46it/s]

In [8]:
#portfolio.plot_leverages()

In [9]:
#{product.isin: product.base_price_change_per_annum for product in portfolio.future_product_instances}

In [10]:
#long_avail_frame = portfolio.get_leverage_availability("long", hour_minute_to_check=(20, 0))
#short_avail_frame = portfolio.get_leverage_availability("short", hour_minute_to_check=(20, 0))

## Predictors

In [11]:
lstm_predictor_list = [LSTMPredictor(model_load_file_path=model_file,
                                     price_csv_path=price_file,
                                     preset_type=pred_type,
                                     name=name,
                                     ) for model_file, price_file, pred_type, name in
                       zip([SAVED_B1_LSTM_PRED_556, SAVED_B2_LSTM_PRED_557, SAVED_C1_LSTM_PRED_619, SAVED_C2_LSTM_PRED_705,
                            SAVED_D1_LSTM_PRED_667, SAVED_D2_LSTM_PRED_792, SAVED_D3_LSTM_PRED_911],
                           [B_PRICE_FILE] * 2 + [C_PRICE_FILE] * 2 + [D_PRICE_FILE] * 3,
                           ["b1", "b2", "c1", "c2", "d1", "d2", "d3"],
                           ["b1_LSTM_HR556", "b2_LSTM_HR557", "c1_LSTM_HR619", "c2_LSTM_HR705", "d1_LSTM_HR667", "d2_LSTM_HR792", "d3_LSTM_HR911"],
                           )]
b1_LSTM_HR556, b2_LSTM_HR557, c1_LSTM_HR619, c2_LSTM_HR705, d1_LSTM_HR667, d2_LSTM_HR792, d3_LSTM_HR911 = lstm_predictor_list

No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.

In [12]:
tf_predictor_list = [TransformerPredictor(model_load_file_path=model_file,
                                          price_csv_path=price_file,
                                          preset_type=pred_type,
                                          name=name,
                                          ) for model_file, price_file, pred_type, name in
                     zip([SAVED_B1_TF_PRED_542, SAVED_D2_TF_PRED_613, SAVED_D3_TF_PRED_743],
                         [B_PRICE_FILE] + [D_PRICE_FILE] * 2,
                         ["b1", "d2", "d3"],
                         ["b1_TF_HR542", "d2_TF_HR613", "d3_TF_HR723"],
                         )]
b1_TF_HR542, d2_TF_HR613, d3_TF_HR723 = tf_predictor_list

No training epochs defined upon initialisation. Define n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define n_train_epochs to start training procedure.

## Environment
https://github.com/tmorgan4/btgym_Kismuz/blob/master/btgym/strategy/base.py

In [19]:
def env_parametrisation_loop(env_price_file_path: Path,
                             env_price_sampling_rate_minutes: int,
                             env_product_set: KOCertificateSet,
                             agent_potential_threshold_steps: (float, float, float) = (.03, .1, .7),
                             sort_metric: Literal['Mean', 'Median', 'StdDev', 'Min', 'Max', 'SharpeRatio'] = 'Mean',
                             print_progress: bool = True,
                             **param_grid_and_constants):
    """
    Backtest multiple hyperparameter settings for RLTradingEnv class.

    Automatically infers parameter grid from provided keyword arguments.

    Provide lists of values for parameters to vary, and single values for constants.
    """
    # Identify grid parameters (iterables) and constant parameters
    grid_params = {k: v for k, v in param_grid_and_constants.items() if isinstance(v, list)}
    constant_params = {k: v for k, v in param_grid_and_constants.items() if k not in grid_params}

    # result frame with columns for all varying parameters and resulting metrics:
    columns = list(grid_params.keys()) + ['Mean', 'Median', 'StdDev', 'Min', 'Max', 'SharpeRatio']
    result_array = []  # initialise result array

    # all possible ordered pairs of grid parameters:
    n_configs = len(list(product(*grid_params.values())))
    for config_ind, config in enumerate(product(*grid_params.values())):
        if print_progress: print(f"\n--------- Backtest Config {config_ind + 1} / {n_configs} ---------")
        
        params = dict(zip(grid_params.keys(), config))
        env_kwargs = {
            **params,
            **constant_params,
            'verbose': False,
            'price_csv_path': env_price_file_path,
            'price_sampling_rate_minutes': env_price_sampling_rate_minutes,
            'product_set': env_product_set,
        }
        
        agent_kwargs = {}
        try:  # if agent potential threshold steps defined in env, add to agent_kwargs dict and remove from env_kwargs
            agent_kwargs['abs_potential_threshold_steps'] = env_kwargs['abs_potential_threshold_steps']
            del env_kwargs['abs_potential_threshold_steps']
        except KeyError:
            pass

        try:
            temp_env = RLTradingEnv(**env_kwargs)

            temp_agent = MultiProductAgent(**agent_kwargs,
                                           # infer other parameters from environment
                                           observation_types=temp_env.observation_types,
                                           observation_horizons_minute=temp_env.observation_horizons_minutes,
                                           n_leverage_categories=len(temp_env.leverage_categories),
                                           include_open_leverage_category=temp_env.include_open_leverage_category,
                                           potential_treshold_horizon_days=temp_env.potential_horizon_days, )

            # settings and losses:
            _, _, metric_tuple = temp_env.run_env_backtest(temp_agent, mute_environment=True, reset_environment=True,
                                                           track_portfolio_exposure_every=100000,
                                                           plot_results=False)
        except (ValueError, AttributeError) as e:
            print("Caught an exception:", e)
            metric_tuple = (np.nan, np.nan, np.nan, np.nan, np.nan, np.nan)
        
        # convert np values to regular values and concat to result row:
        metric_list = [metric.item() if isinstance(metric, np.float64) else metric for metric in metric_tuple]
        result_row = list(config) + metric_list
        result_array.append(result_row)  # append to result_array

    # convert to frame and sort eventually:
    results = pd.DataFrame(result_array, columns=columns)
    if sort_metric is not None:
        minimize = sort_metric in ['StdDev']
        results = results.sort_values(by=sort_metric, ascending=minimize)

    return results

In [20]:
print(lstm_predictor_list)
print(tf_predictor_list)

[b1_LSTM_HR556, b2_LSTM_HR557, c1_LSTM_HR619, c2_LSTM_HR705, d1_LSTM_HR667, d2_LSTM_HR792, d3_LSTM_HR911]
[b1_TF_HR542, d2_TF_HR613, d3_TF_HR723]

In [21]:
result_frame = env_parametrisation_loop(env_price_file_path=ENV_PRICE_FILE, env_price_sampling_rate_minutes=15,
                                        env_product_set=portfolio,
                                        # varying params:
                                        predictor_instances=[#[d3_LSTM_HR911],  # great predictors on their own
                                                             #[d2_LSTM_HR792],
                                                             [c2_LSTM_HR705], #
                                                             #[d3_TF_HR723],
                                                             # combinations:
                                                             [c2_LSTM_HR705, d2_LSTM_HR792, d3_LSTM_HR911, d3_TF_HR723],  #
                                                             # all above 70
                                                             #[d3_LSTM_HR911, d3_TF_HR723],  # both architectures D3
                                                             #[d2_LSTM_HR792, d2_TF_HR613],  # both architectures D2
                                                             #[b1_LSTM_HR556, b1_TF_HR542],  # both architectures b1
                                                             #[b1_LSTM_HR556, b2_LSTM_HR557, b1_TF_HR542],
                                                             # all short term
                                                             #[c1_LSTM_HR619, c2_LSTM_HR705],  # all mid term
                                                             [d1_LSTM_HR667, d2_LSTM_HR792, d3_LSTM_HR911, d2_TF_HR613, d3_TF_HR723],  # all long term  #
                                                             #lstm_predictor_list,  # all LSTMs
                                                             #tf_predictor_list,  # all transformers
                                                             lstm_predictor_list + tf_predictor_list,  # all predictors  #
                                                             ],

                                        # constant params:
                                        # 90 day expected return, sell -> buy -> highest leverage
                                        abs_potential_threshold_steps = [(.0025, .0075, .015), (.002, .004, .01), (.003, .01, .02)],
                                        # balanced, offensive, defensive
                                        trading_quantity_per_leverage_factor=1,
                                        sell_opposite_direction_if_no_cash=True,
                                        sell_all_opposite_products_if_no_cash=True,  #[False, True],
                                        include_open_leverage_category=False,
                                        precalculate_predictor_observations=True,
                                        leverage_categories=(1.0, 2.0, 3.0, 4.0, 5.0))
result_frame

--------- Backtest Config 1 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [00:27<00:00, 101.36it/s]
100%|█████████▉| 2729/2730 [13:28<00:00,  3.38it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 13.388%		Mean 17.452%	Std.Dev. 22.678%
			Max. 161.416%		Min. -21.451%
Alpha:		Median 12.629%		Mean 16.621%	Std.Dev. 23.616%
			Max. 180.874%		Min. -29.627%
Sharpe Ratio: 4.801 - Annual Sharpe Ratio: 28.808
Over-performed 102 / 127 epochs

--------- Backtest Config 2 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [00:26<00:00, 104.49it/s]
100%|█████████▉| 2729/2730 [11:48<00:00,  3.85it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 14.059%		Mean 17.393%	Std.Dev. 22.89%
			Max. 161.416%		Min. -21.166%
Alpha:		Median 12.583%		Mean 16.562%	Std.Dev. 23.892%
			Max. 180.874%		Min. -29.342%
Sharpe Ratio: 4.754 - Annual Sharpe Ratio: 28.527
Over-performed 100 / 127 epochs

--------- Backtest Config 3 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [00:25<00:00, 107.13it/s]
100%|█████████▉| 2729/2730 [11:41<00:00,  3.89it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 13.502%		Mean 16.837%	Std.Dev. 22.63%
			Max. 161.417%		Min. -21.369%
Alpha:		Median 12.57%		Mean 16.006%	Std.Dev. 23.753%
			Max. 180.875%		Min. -29.545%
Sharpe Ratio: 4.785 - Annual Sharpe Ratio: 28.707
Over-performed 101 / 127 epochs

--------- Backtest Config 4 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [02:09<00:00, 21.37it/s]
100%|█████████▉| 2433/2434 [13:52<00:00,  2.92it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 12.752%		Mean 16.702%	Std.Dev. 24.664%
			Max. 145.955%		Min. -97.555%
Alpha:		Median 10.219%		Mean 15.582%	Std.Dev. 26.606%
			Max. 165.413%		Min. -120.627%
Sharpe Ratio: 4.384 - Annual Sharpe Ratio: 26.306
Over-performed 94 / 113 epochs

--------- Backtest Config 5 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [02:24<00:00, 19.18it/s]
100%|█████████▉| 2433/2434 [13:19<00:00,  3.04it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 12.752%		Mean 17.546%	Std.Dev. 26.681%
			Max. 179.661%		Min. -97.555%
Alpha:		Median 11.341%		Mean 16.426%	Std.Dev. 28.628%
			Max. 199.119%		Min. -120.627%
Sharpe Ratio: 4.085 - Annual Sharpe Ratio: 24.507
Over-performed 94 / 113 epochs

--------- Backtest Config 6 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [02:16<00:00, 20.30it/s]
100%|█████████▉| 2433/2434 [13:20<00:00,  3.04it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 12.247%		Mean 16.748%	Std.Dev. 25.688%
			Max. 179.661%		Min. -90.504%
Alpha:		Median 11.326%		Mean 15.629%	Std.Dev. 27.682%
			Max. 199.119%		Min. -113.576%
Sharpe Ratio: 4.211 - Annual Sharpe Ratio: 25.269
Over-performed 93 / 113 epochs

--------- Backtest Config 7 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [03:00<00:00, 15.37it/s]
100%|█████████▉| 2433/2434 [16:33<00:00,  2.45it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 6.865%		Mean 7.417%	Std.Dev. 21.054%
			Max. 74.028%		Min. -108.084%
Alpha:		Median 6.099%		Mean 6.297%	Std.Dev. 21.929%
			Max. 72.836%		Min. -131.156%
Sharpe Ratio: 4.695 - Annual Sharpe Ratio: 28.171
Over-performed 73 / 113 epochs

--------- Backtest Config 8 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [03:14<00:00, 14.25it/s]
100%|█████████▉| 2433/2434 [16:00<00:00,  2.53it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 7.192%		Mean 7.302%	Std.Dev. 20.957%
			Max. 78.736%		Min. -108.084%
Alpha:		Median 7.285%		Mean 6.182%	Std.Dev. 21.857%
			Max. 76.266%		Min. -131.156%
Sharpe Ratio: 4.711 - Annual Sharpe Ratio: 28.268
Over-performed 72 / 113 epochs

--------- Backtest Config 9 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [03:15<00:00, 14.18it/s]
100%|█████████▉| 2433/2434 [16:36<00:00,  2.44it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 7.263%		Mean 6.729%	Std.Dev. 20.361%
			Max. 56.966%		Min. -108.084%
Alpha:		Median 6.114%		Mean 5.609%	Std.Dev. 21.219%
			Max. 69.785%		Min. -131.156%
Sharpe Ratio: 4.821 - Annual Sharpe Ratio: 28.927
Over-performed 71 / 113 epochs

--------- Backtest Config 10 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [10:16<00:00,  4.49it/s]
100%|█████████▉| 2433/2434 [17:54<00:00,  2.26it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 5.101%		Mean 6.436%	Std.Dev. 24.416%
			Max. 192.247%		Min. -37.391%
Alpha:		Median 3.991%		Mean 5.316%	Std.Dev. 25.185%
			Max. 211.705%		Min. -38.106%
Sharpe Ratio: 4.009 - Annual Sharpe Ratio: 24.051
Over-performed 68 / 113 epochs

--------- Backtest Config 11 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [09:51<00:00,  4.68it/s]
100%|█████████▉| 2433/2434 [17:27<00:00,  2.32it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 4.797%		Mean 6.6%	Std.Dev. 24.92%
			Max. 200.957%		Min. -37.387%
Alpha:		Median 3.984%		Mean 5.48%	Std.Dev. 25.643%
			Max. 220.414%		Min. -38.129%
Sharpe Ratio: 3.934 - Annual Sharpe Ratio: 23.603
Over-performed 69 / 113 epochs

--------- Backtest Config 12 / 12 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [09:51<00:00,  4.69it/s]
100%|█████████▉| 2433/2434 [17:42<00:00,  2.29it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 4.778%		Mean 6.448%	Std.Dev. 25.224%
			Max. 201.41%		Min. -37.383%
Alpha:		Median 3.978%		Mean 5.329%	Std.Dev. 26.084%
			Max. 220.868%		Min. -37.754%
Sharpe Ratio: 3.881 - Annual Sharpe Ratio: 23.283
Over-performed 68 / 113 epochs

,predictor_instances,abs_potential_threshold_steps,Mean,Median,StdDev,Min,Max,SharpeRatio
0,[c2_LSTM_HR705],"(0.0025, 0.0075, 0.015)",0.166210,0.126287,0.236164,-0.296271,1.808744,4.801372
1,[c2_LSTM_HR705],"(0.002, 0.004, 0.01)",0.165623,0.125835,0.238924,-0.293420,1.808744,4.754465
4,"[c2_LSTM_HR705, d2_LSTM_HR792, d3_LSTM_HR911, ...","(0.002, 0.004, 0.01)",0.164257,0.113405,0.286280,-1.206265,1.991190,4.084578
2,[c2_LSTM_HR705],"(0.003, 0.01, 0.02)",0.160055,0.125705,0.237533,-0.295446,1.808749,4.784518
5,"[c2_LSTM_HR705, d2_LSTM_HR792, d3_LSTM_HR911, ...","(0.003, 0.01, 0.02)",0.156286,0.113261,0.276824,-1.135760,1.991190,4.211434
3,"[c2_LSTM_HR705, d2_LSTM_HR792, d3_LSTM_HR911, ...","(0.0025, 0.0075, 0.015)",0.155821,0.102189,0.266059,-1.206265,1.654129,4.384414
6,"[d1_LSTM_HR667, d2_LSTM_HR792, d3_LSTM_HR911, ...","(0.0025, 0.0075, 0.015)",0.062973,0.060993,0.219292,-1.311557,0.728362,4.695224
7,"[d1_LSTM_HR667, d2_LSTM_HR792, d3_LSTM_HR911, ...","(0.002, 0.004, 0.01)",0.061818,0.072853,0.218565,-1.311557,0.762656,4.711280
8,"[d1_LSTM_HR667, d2_LSTM_HR792, d3_LSTM_HR911, ...","(0.003, 0.01, 0.02)",0.056087,0.061141,0.212187,-1.311558,0.697847,4.821231
10,"[b1_LSTM_HR556, b2_LSTM_HR557, c1_LSTM_HR619, ...","(0.002, 0.004, 0.01)",0.054801,0.039842,0.256431,-0.381285,2.204145,3.933906
11,"[b1_LSTM_HR556, b2_LSTM_HR557, c1_LSTM_HR619, ...","(0.003, 0.01, 0.02)",0.053285,0.039780,0.260843,-0.377540,2.208682,3.880563
9,"[b1_LSTM_HR556, b2_LSTM_HR557, c1_LSTM_HR619, ...","(0.0025, 0.0075, 0.015)",0.053163,0.039913,0.251847,-0.381064,2.117046,4.008518

In [16]:
env = RLTradingEnv(ENV_PRICE_FILE,
                   price_sampling_rate_minutes=15,
                   # only predictors with val HR > 66%
                   predictor_instances=[c2_LSTM_HR705],
                   product_set=portfolio, trading_quantity_per_leverage_factor=1,
                   sell_opposite_direction_if_no_cash=True, sell_all_opposite_products_if_no_cash=True,
                   include_open_leverage_category=False,
                   precalculate_predictor_observations=True,  # FALSE MAKES SENSE ONLY FOR REDUCED N_STEPS IN BACKTEST
                   leverage_categories=(1.0, 2.0, 3.0, 4.0, 5.0))  #, 5.5, 6.0, 6.5, 7.0))

Starting at 2014-12-18 although data is provided since 2014-10-23 to have sufficient information for all predictors.

In [20]:
"""obs, _, _, _, info = env.step(10, track_portfolio_exposure=False)
print(obs)
print(info)
#self.open_positions"""

'obs, _, _, _, info = env.step(10, track_portfolio_exposure=False)\nprint(obs)\nprint(info)\n#self.open_positions'

## Agent

### Manual Agent

In [15]:
agent = MultiProductAgent(observation_types=env.observation_types,
                          observation_horizons_minute=env.observation_horizons_minutes,
                          n_leverage_categories=len(env.leverage_categories),
                          abs_potential_threshold_steps=(.03, .1, .7),  # (.04, .15, .7)
                          include_open_leverage_category=env.include_open_leverage_category,
                          potential_treshold_horizon_days=env.potential_horizon_days,
                          )

### RL Agent
With stable-baseline3 and pytorch.

Stable-Baselines3 is a reinforcement learning library built on top of PyTorch. It provides a set of pre-implemented RL algorithms and simplifies the process of training and evaluating RL models. It also includes a variety of useful tools for monitoring training progress and visualizing model behavior.

For training we will use Deep Q-Network (DQN). DQN is a reinforcement learning algorithm that uses a deep neural network to approximate the Q-value function. The Q-value function is a function that receives a status-action pair and outputs a value representing the expected cumulative reward for taking that action from that status, and continues playing following the optimal policy.

#### Agent Training

In [23]:
from stable_baselines3.common.env_checker import check_env
# check_env(env)

In [25]:
# MlpPolicy is policy used for training
# DummyVecEnc optimizes training through multiple independent variables
env.verbose = False  # mute environment
rl_agent = DQN('MlpPolicy', DummyVecEnv([lambda: env]), learning_rate=0.001, verbose=1)

Using cpu device

In [26]:
rl_agent.learn(total_timesteps=50000, log_interval=100, progress_bar=True)  # ~1s per iteration -> ~3600 iterations/h
rl_agent.save(filemgmt.file_title('DQN Trading Agent 100k iterations', dtype_suffix='.pt'))

Output()

In [ ]:
# only decision 'sell long 2.0-3.0' in backtest... what can cause stagnant decision-making?

In [25]:
# ponder:
# - training visualisation
# - reward shaping
# - initialisation
# - architecture

## Backtest

In [28]:
monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=rl_agent, track_portfolio_exposure_every=20,
                                                         reset_environment=True,
                                                         save_log_directory=TRAINING_LOGS, performance_time_unit='p.m.')

100%|█████████▉| 2433/2434 [24:55<00:00,  1.63it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median -0.0003775623638226969	Mean -0.017217729742190827	Std.Dev. 0.062366558744278086
			Max. 0.13920729313452138	Min. -0.31797556580127434
Alpha: 	Median -0.01720177719876938	Mean -0.02841588967384051	Std.Dev. 0.10478604041982394
			Max. 0.2895693743967548	Min. -0.3637487042342834
Over-performed 48 / 113 epochs

NameError: name 'monthly_policy' is not defined

In [ ]:
# instead: fill alpha area green or red instead of extra line

In [17]:
env.current_step = 2600

In [18]:
monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=agent, track_portfolio_exposure_every=20,
                                                                     reset_environment=False,
                                                                     save_log_directory=TRAINING_LOGS,
                                                                     performance_time_unit='p.m.')

 99%|█████████▉| 169/170 [01:07<00:00,  2.49it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 12.465%		Mean 18.607%	Std.Dev. 24.529%
			Max. 81.031%		Min. -0.807%
Alpha:		Median 5.266%		Mean 13.615%	Std.Dev. 25.602%
			Max. 76.209%		Min. -10.607%
Sharpe Ratio: 4.486 - Annual Sharpe Ratio: 26.918
Over-performed 7 / 9 epochs

In [20]:
frame = pd.read_csv(filemgmt.most_recent_file(TRAINING_LOGS, file_title_keyword="Backtest Log"))
frame
#frame['Time'] = pd.to_datetime(frame['Time'])

,Time,Step,Reward,Action,Avg. Expected Potential / 90d,Cash,Total,Total Exposure,Time.1,Benchmark
0,2024-10-11 16:00:00,2601,-183.74,Buy short 1.0x - 2.0x,-0.054769,816074.69,999816.26,-0.204548,2024-10-11 16:00:00,1.000000e+06
1,2024-10-14 16:00:00,2602,-1277.41,Sell long 3.0x - 4.0x,-0.107810,816074.69,998538.85,NaN,2024-10-14 16:00:00,1.006393e+06
2,2024-10-15 16:00:00,2603,-948.00,Buy short 1.0x - 2.0x,-0.215820,617642.57,997590.85,NaN,2024-10-15 16:00:00,1.010207e+06
3,2024-10-16 16:00:00,2604,2940.04,Buy short 1.0x - 2.0x,-0.084681,417570.60,1000530.89,NaN,2024-10-16 16:00:00,1.003011e+06
4,2024-10-17 16:00:00,2605,-653.63,Sell long 1.0x - 2.0x,0.310321,417570.60,999877.26,NaN,2024-10-17 16:00:00,1.004163e+06
...,...,...,...,...,...,...,...,...,...,...
164,2025-05-29 16:00:00,2765,-6012.97,Buy short 1.0x - 2.0x,-0.045658,1427161.73,3504763.47,NaN,2025-05-29 16:00:00,1.286687e+06
165,2025-05-30 16:00:00,2766,1523.73,Sell long 4.0x - 5.0x,0.030953,1427161.73,3506287.20,NaN,2025-05-30 16:00:00,1.287564e+06
166,2025-06-02 16:00:00,2767,-7386.52,Sell short 4.0x - 5.0x,0.017005,1427161.73,3498900.68,NaN,2025-06-02 16:00:00,1.282450e+06
167,2025-06-03 16:00:00,2768,9564.69,Hold,0.143870,1427161.73,3508465.37,NaN,2025-06-03 16:00:00,1.288733e+06
168,2025-06-04 16:00:00,2769,19511.44,Buy long 1.0x - 2.0x,-0.001926,724375.35,3527976.81,NaN,2025-06-04 16:00:00,1.302175e+06

In [21]:
def plot_backtest_results(self, log_df: pd.DataFrame,
                          policy_return_series: pd.Series = None,
                          benchmark_return_series: pd.Series = None,
                          performance_time_unit: Literal['p.a.', 'p.m.'] = 'p.a.',
                          agent: Union[MultiProductAgent, DQN] = None,
                          save_fig_directory: str = None):
    """
    Visualize backtest results.

    Include monthly or annual returns as policy_return_series to include time-normalized return plot.
    """
    # prepare axes:
    if policy_return_series is not None:
        fig, (return_ax, performance_ax, exposure_ax, cash_ax) = plt.subplots(4, 1, figsize=(16, 13))
    else:
        fig, (return_ax, exposure_ax, cash_ax) = plt.subplots(3, 1, figsize=(16, 13))
    potential_ax = exposure_ax.twinx()
    dates = pd.to_datetime(log_df.index)

    # portfolio performance:
    val_df = log_df.loc[:,
             [f'Avg. Expected Potential / {self.potential_horizon_days}d', 'Total Exposure', 'Cash', 'Total']]
    normalized_policy_portfolio_value = log_df['Total'] / log_df['Benchmark'].iloc[0]
    normalized_benchmark_portfolio_value = log_df['Benchmark'] / log_df['Benchmark'].iloc[0]
    return_ax.plot(dates, normalized_policy_portfolio_value, color='orange', label='Policy')
    return_ax.plot(dates, normalized_benchmark_portfolio_value, color='blue', label='Benchmark')
    return_ax.set_title('Normalized Policy vs. Benchmark Portfolio Value')
    return_ax.set_xlabel('Date')
    return_ax.set_ylabel('Normalized Balance')
    return_ax.legend()
    return_ax.grid(True)

    # relative (time-normalised) performance plot:
    if policy_return_series is not None:
        performance_ax.plot(policy_return_series * 100, marker='o', color='orange', label='Policy')
        if benchmark_return_series is not None:
            performance_ax.plot(benchmark_return_series * 100, marker='o', color='blue', label='Benchmark')

            performance_ax.fill_between(policy_return_series.index, benchmark_return_series*100,
                                        policy_return_series*100,
                                        where=(policy_return_series>benchmark_return_series),
                                        edge_color='green', color='green', alpha=.5,
                                        label='Over-performance')
            performance_ax.fill_between(policy_return_series.index, benchmark_return_series*100,
                                        policy_return_series*100,
                                        where=(policy_return_series<benchmark_return_series),
                                        edge_color='red', color='red', alpha=.5,
                                        label='Under-performance')
            
            performance_ax.axhline(y=0, color='black')
        performance_ax.set_xlabel('Datetime');
        performance_ax.set_ylabel(f"Return {performance_time_unit} [%]")
        performance_ax.legend(loc='upper left')
        performance_ax.grid()

    # include potential thresholds:
    potentials = val_df[f'Avg. Expected Potential / {self.potential_horizon_days}d'] * 100
    if isinstance(agent, MultiProductAgent):
        # scale and derive thresholds:
        scaled_thresholds = [threshold * sign * 100 for threshold, sign in
                             product(agent.abs_potential_threshold_steps, [-1, 1])]
        # plot threshold lines:
        for ind, scaled_threshold in enumerate(scaled_thresholds):
            potential_ax.axhline(y=scaled_threshold, color='purple',
                                 linestyle=':', alpha=.3,
                                 label='Action Thresholds' if ind == 0 else '_',
                                 # create legend entry only for first line
                                 )

        # avg potential:
        potentials = val_df[f'Avg. Expected Potential / {self.potential_horizon_days}d'] * 100
        buy_long_signals = np.where(potentials > scaled_thresholds[3], potentials, np.nan)
        potential_ax.plot(dates, buy_long_signals, color='green', label='Buy Long Signal')
        sell_short_signals = np.where((potentials > scaled_thresholds[1]) & (potentials < scaled_thresholds[3]),
                                      potentials, np.nan)
        potential_ax.plot(dates, sell_short_signals, color='lightgreen', label='Sell Short Signal')
        hold_signals = np.where((potentials > scaled_thresholds[0]) & (potentials < scaled_thresholds[1]),
                                      potentials, np.nan)
        potential_ax.plot(dates, hold_signals, color='grey', label='Hold Signal')
        sell_long_signals = np.where((potentials > scaled_thresholds[2]) & (potentials < scaled_thresholds[0]),
                                     potentials, np.nan)
        potential_ax.plot(dates, sell_long_signals, color='lightcoral', label='Sell Long Signal')
        buy_short_signals = np.where(potentials < scaled_thresholds[2], potentials, np.nan)
        potential_ax.plot(dates, buy_short_signals, color='red', label='Buy Short Signal')
    else:  # if agent doesn't follow a manual agenda:
        potential_ax.plot(dates, potentials, color='green', label='Expected Potential')

    # portfolio exposure:
    exposure_ax.plot(dates, val_df['Total Exposure'], color='black', label='Portfolio Exposure', marker='o',
                     markersize=5)

    # cash quote:
    cash_percent = (val_df['Cash'] / val_df['Total']) * 100
    cash_ax.plot(dates, cash_percent, color='black', label='Cash Quote [%]')
    cash_ax.fill_between(dates, 0, cash_percent, color='grey', alpha=.15, label='Cash')
    cash_ax.fill_between(dates, cash_percent, 100, color='purple', alpha=.15, label='Stock Holding')
    cash_ax.set_ylim([0, 100])
    cash_ax.set_xlabel('Date');
    cash_ax.set_ylabel('Share of Total Portfolio [%]')
    cash_ax.set_title('Portfolio Composition Cash vs. Holding')
    cash_ax.legend(loc='upper left');
    cash_ax.grid(True)

    # formatting:
    exposure_ax.set_xlabel('Date')
    exposure_ax.legend(loc='upper left');
    potential_ax.legend(loc='lower right')
    exposure_ax.set_ylabel('Total Exposure [x]');
    potential_ax.set_ylabel(f'Expected Forward Potential / {self.potential_horizon_days}d [%]')
    exposure_ax.set_ylim([-5, 5])
    max_potential = np.max(val_df[f'Avg. Expected Potential / {self.potential_horizon_days}d'] * 100);
    potential_ax.set_ylim([-100, 100])
    exposure_ax.set_title('Portfolio Exposure and Predicted Potential')
    exposure_ax.grid(True)

    fig.tight_layout()

    if save_fig_directory is not None:  # eventually save result plot:
        plt.savefig(save_fig_directory / filemgmt.file_title("Backtest Result Visualisation", ".png"))

    plt.show()

In [25]:
import matplotlib.pyplot as plt
plot_backtest_results(env, frame.set_index('Time'))

In [25]:
frame

,Time,Step,Reward,Action,Avg. Expected Potential / 90d,Cash,Total,Total Exposure,Benchmark,Time.1
0,2024-10-14 16:00:00,2602,3922.54,Sell long 4.0x - 5.0x,-0.015391,10526.26,627978.77,NaN,NaN,2024-10-14 16:00:00
1,2024-10-15 16:00:00,2603,2339.60,Hold,-0.034034,10526.26,630318.37,NaN,NaN,2024-10-15 16:00:00
2,2024-10-16 16:00:00,2604,-4414.78,Sell long 4.0x - 5.0x,0.009697,10526.26,625903.59,NaN,NaN,2024-10-16 16:00:00
3,2024-10-17 16:00:00,2605,706.59,Hold,0.114231,10526.26,626610.18,NaN,NaN,2024-10-17 16:00:00
4,2024-10-18 16:00:00,2606,596.48,Buy long 1.0x - 2.0x,0.096086,10526.26,627206.66,NaN,NaN,2024-10-18 16:00:00
...,...,...,...,...,...,...,...,...,...,...
163,2025-05-29 16:00:00,2765,304.25,Buy short 1.0x - 2.0x,-0.206763,677507.84,1087850.75,NaN,NaN,2025-05-29 16:00:00
164,2025-05-30 16:00:00,2766,-462.98,Buy short 1.0x - 2.0x,-0.241880,472260.31,1087387.77,NaN,NaN,2025-05-30 16:00:00
165,2025-06-02 16:00:00,2767,2748.41,Buy short 1.0x - 2.0x,-0.147841,266026.98,1090136.18,NaN,NaN,2025-06-02 16:00:00
166,2025-06-03 16:00:00,2768,-4741.25,Buy short 1.0x - 2.0x,-0.087222,60928.88,1085394.93,NaN,NaN,2025-06-03 16:00:00
167,2025-06-04 16:00:00,2769,-12325.97,Sell long 1.0x - 2.0x,-0.177217,60928.88,1073068.97,NaN,NaN,2025-06-04 16:00:00

In [28]:
type(pd.to_datetime(frame.set_index('Time').index))

pandas.core.indexes.datetimes.DatetimeIndex

In [22]:
isinstance(frame.set_index('Time').index, pd.DatetimeIndex)

True

In [19]:
env.plot_backtest_results(frame.set_index('Time'), plot_annual_returns=False)

Over-performed 53.09734513274337% of months

In [104]:
import matplotlib.pyplot as plt

plot_annual_returns = False
plot_size = (12, 5)

frame['Time'] = pd.to_datetime(frame.Time)
annual_return_frame = frame.loc[:, ['Total', 'Benchmark', 'Time']].groupby(frame.Time.dt.year if plot_annual_returns else [frame.Time.dt.year, frame.Time.dt.month]).agg(['first', 'last'])
annual_return_frame['Benchmark return'] = ((annual_return_frame['Benchmark', 'last'] - annual_return_frame['Benchmark', 'first']) / annual_return_frame['Benchmark', 'first']) * (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first']).max() / (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first'])

annual_return_frame['Policy return'] = (annual_return_frame['Total', 'last'] - annual_return_frame['Total', 'first']) / annual_return_frame['Total', 'first'] * (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first']).max() / (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first'])  # calculate relative development and normalise by time-duration
annual_return_frame['Over performance'] = annual_return_frame['Policy return'] > annual_return_frame['Benchmark return']

# result plot:
fig, ax = plt.subplots(figsize=plot_size)
ax2 = ax.twinx()
ax.plot(annual_return_frame.set_index([('Time', 'first')]).loc[:, ['Benchmark return', 'Policy return']] * 100, marker='o', label=['Benchmark', 'Policy'])
ax.set_xlabel('Datetime'); ax.set_ylabel(f"Return per {'annum' if plot_annual_returns else 'month'} [%]")
annual_return_frame['Over performance'] = annual_return_frame['Policy return'] > annual_return_frame['Benchmark return']

ax2.plot(annual_return_frame.set_index([('Time', 'first')]).loc[:, 'Over performance'], marker='s', linestyle='', color='Black')
ax2.set_ylabel('Performance Policy vs Benchmark')
ax2.set_yticks([0, 1]); ax2.set_yticklabels(['Under', 'Over'])
ax.legend(bbox_to_anchor=(0.5, -.3), loc='lower center')
print(f"Over-performed {annual_return_frame['Over performance'].value_counts()[True].item()/len(annual_return_frame)*100}% of {'years' if plot_annual_returns else 'months'}")
ax.grid()
fig.tight_layout()

Over-performed 53.09734513274337% of months

In [98]:
annual_return_frame['Over performance'].value_counts()[True].item()

6

In [50]:
annual_return_frame

            Total                  Benchmark                \
            first         last         first          last
Time
2016   1000000.00   1125538.30  1.000000e+06  1.184353e+06
2017   1129008.79   1348508.57  1.180851e+06  1.504055e+06
2018   1351917.95   1720917.53  1.507863e+06  1.182703e+06
2019   1740774.20   1468683.64  1.164954e+06  1.410989e+06
2020   1491072.99   7842089.90  1.432583e+06  1.601698e+06
2021   7859483.70   9479701.75  1.604761e+06  1.717990e+06
2022   9468268.84  11291636.06  1.730214e+06  1.410605e+06
2023  11217780.60  10291309.92  1.424105e+06  1.745433e+06
2024  10287803.99  12133463.31  1.734652e+06  1.926743e+06
2025  12153677.13  19272621.34  1.919826e+06  2.568497e+06

                    Time                     Benchmark p.a. Policy p.a.
                   first                last
Time
2016 2016-02-08 16:00:00 2016-12-30 16:00:00       0.184353    0.125538
2017 2017-01-02 16:00:00 2017-12-29 16:00:00       0.273704    0.194418
2018 2018-01-01 16:00:00 2018-12-31 16:00:00      -0.215642    0.272945
2019 2019-01-01 16:00:00 2019-12-31 16:00:00       0.211197   -0.156304
2020 2020-01-01 16:00:00 2020-12-31 16:00:00       0.118049    4.259360
2021 2021-01-01 16:00:00 2021-12-31 16:00:00       0.070558    0.206148
2022 2022-01-03 16:00:00 2022-12-30 16:00:00      -0.184722    0.192577
2023 2023-01-02 16:00:00 2023-12-29 16:00:00       0.225635   -0.082589
2024 2024-01-01 16:00:00 2024-12-31 16:00:00       0.110737    0.179403
2025 2025-01-01 16:00:00 2025-06-04 16:00:00       0.337880    0.585744

In [60]:
import matplotlib.pyplot as plt
annual_return_frame['Benchmark p.a.'] = ((annual_return_frame['Benchmark', 'last'] - annual_return_frame['Benchmark', 'first']) / annual_return_frame['Benchmark', 'first']) * (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first']).max() / (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first'])
annual_return_frame['Policy p.a.'] = (annual_return_frame['Total', 'last'] - annual_return_frame['Total', 'first']) / annual_return_frame['Total', 'first'] * (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first']).max() / (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first'])  # calculate relative development and normalise by time-duration
fig, ax = plt.subplots()
ax.plot(annual_return_frame.set_index([('Time', 'first')]).loc[:, ['Policy p.a.', 'Benchmark p.a.']], marker='o')

[<matplotlib.lines.Line2D at 0x38586ec10>,
 <matplotlib.lines.Line2D at 0x38586ed50>]

In [58]:
annual_return_frame.set_index('Time')

KeyError: "None of ['first'] are in the columns"

## Run

NameError: name 'env' is not defined

In [ ]:
# add recent price data:
# env.price_csv_path = filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '15min')

In [20]:
# set current step to latest step:
env.current_step = env.total_steps - 1
env.current_step_timestamp

Timestamp('2025-07-17 16:00:00')

In [22]:
env.average_predicted_potential

0.10184113630236336

In [36]:
env.action_enum_dict[agent.predict(env.current_observation)[0]]

'Sell short 3.0x - 4.0x'